/// 阿拉伯语
Map<String, String> ar = {
  'app_service.language': 'لغة',
  'app_service.languages': 'اللغات',
  'app_service.select_language': 'اختر اللغة',
  'app_service.language_tag': 'علامة اللغة',
  'app_service.:': ' : ',
  'app_service.settings': 'الإعدادات',
  'app_service.close': 'إغلاق',
  'app_service.lang': 'اللغة',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'السمة',
  'app_service.color_theme': 'سمة الألوان',
  'app_service.dark_mode': 'الوضع الداكن',
  'app_service.sys_lang': 'لغة النظام',
  'app_service.select_theme': 'اختيار السمة',
  'app_service.follow_system': 'اتبع النظام',
  // theme
  'aquaBlue': 'أزرق مائي',
  'bahamaTrinidad': 'بهاما ترينيداد',
  'barossa': 'باروسا',
  'amberBlue': 'أزرق كهرماني',
  'bigStoneTulip': 'زنبق الحجر الكبير',
  'blueDelight': 'سعادة زرقاء',
  'blueStoneTeal': 'زرقة الحجر الأزرق',
  'blueWhale': 'حوت أزرق',
  'blumine': 'بلومين',
  'brandBlue': 'أزرق العلامة التجارية',
  'brownOrange': 'بني برتقالي',
  'camaroneGreen': 'أخضر الكامارون',
  'damaskLunar': 'الدمشقي القمري',
  'deepBlueSea': 'البحر الأزرق العميق',
  'deepPurple': 'بنفسجي عميق',
  'dellGenoaGreen': 'أخضر جنوة ديل',
  'ebonyClay': 'طين الأبنوس',
  'eggplantPurple': 'بنفسجي الباذنجان',
  'endeavourBlue': 'أزرق المجهود',
  'espressoCrema': 'كريمة الإسبريسو',
  'flutterDash': 'فراشة داش',
  'goldSunset': 'غروب ذهبي',
  'greens': 'أخضر',
  'greenForest': 'غابة خضراء',
  'greenJungle': 'غابة اخضر',
  'greenMoney': 'نقود خضراء',
  'greyLaw': 'رمادي قانوني',
  'hippieBlue': 'أزرق هيبي',
  'indigoNight': 'ليل النيلي',
  'indigoSanMarino': 'سان مارينو النيلي',
  'lipstickPink': 'وردي أحمر الشفاه',
  'mallardValencia': 'مالارد فالنسيا',
  'mangoMojito': 'موهيتو المانجو',
  'material3': 'مادة 3',
  'material3HighContrast': 'مادة 3 عالية التباين',
  'material3Purple': 'مادة 3 بنفسجي',
  'midnight': 'منتصف الليل',
  'mosqueCyan': 'سيان المسجد',
  'ohMandyRed': 'أحمر أوه ماندي',
  'outerSpace': 'الفضاء الخارجي',
  'pinkSakura': 'ساكورا وردي',
  'purpleBrown': 'بني أرجواني',
  'redBlue': 'أحمر أزرق',
  'redTornado': 'إعصار أحمر',
  'redWine': 'نبيذ أحمر',
  'rosewood': 'خشب الورد',
  'rustDeepOrange': 'البرتقالي العميق الصدأ',
  'sanJuanBlue': 'أزرق سان خوان',
  'sharkOrange': 'أحمر برتقالي',
  'thunderbirdRed': 'أحمر طائر الرعد',
  'verdunGreen': 'أخضر فردان',
  'verdunLime': 'الليمون الفردان',
  'vesuviusBurned': 'محروقة فيزوفيوس',
  'willowWasabi': 'الصفصاف واسابي',
  'yukonGoldYellow': 'أصفر ذهبي يوكون',
};
