/// 阿拉伯语
Map<String, String> ar = {
  'app_service.language_tag': 'علامة اللغة',
  'app_service.:': ' : ',
  'app_service.settings': 'الإعدادات',
  'app_service.close': 'إغلاق',
  'app_service.lang': 'اللغة',
  'app_service.lang.zh': 'الصينية',
  'app_service.lang.zh_Hans': 'الصينية (المبسطة)',
  'app_service.lang.zh-MO': 'الصينية (ماكاو)',
  'app_service.lang.zh-HK': 'الصينية (هونغ كونغ)',
  'app_service.lang.zh-TW': 'الصينية (تايوان)',
  'app_service.lang.en': 'الإنجليزية',
  'app_service.lang.en-US': 'الإنجليزية (US)',
  'app_service.lang.en-GB': 'الإنجليزية (UK)',
  'app_service.lang.fr': 'الفرنسية',
  'app_service.lang.de': 'الألمانية',
  'app_service.lang.de-DE': 'الألمانية (ألمانيا)',
  'app_service.lang.it': 'الإيطالية',
  'app_service.lang.he': 'العبرية',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'الروسية',
  'app_service.lang.ru-RU': 'الروسية (روسيا)',
  'app_service.lang.ru-BY': 'الروسية (بيلاروسيا)',
  'app_service.lang.ru-KZ': 'الروسية (كازاخستان)',
  'app_service.lang.ru-UA': 'الروسية (أوكرانيا)',
  'app_service.lang.uk': 'الأوكرانية',
  'app_service.lang.be': 'البيلاروسية',
  'app_service.lang.kk': 'الكازاخية',
  'app_service.lang.sr': 'الصربية',
  'app_service.lang.ja': 'اليابانية',
  'app_service.lang.ko': 'الكورية',
  'app_service.lang.pt': 'البرتغالية',
  'app_service.lang.nl': 'الهولندية',
  'app_service.lang.tr': 'التركية',
  'app_service.lang.th': 'التايلاندية',
  'app_service.lang.vi': 'الفيتنامية',
  'app_service.lang.ms': 'الماليزية',
  'app_service.lang.pl': 'البولندية',
  'app_service.lang.da': 'الدانماركية',
  'app_service.lang.fi': 'الفنلندية',
  'app_service.lang.la': 'اللاتينية',
  'app_service.lang.no': 'النرويجية',
  'app_service.lang.sk': 'السلوفاكية',
  'app_service.lang.bg': 'البلغارية',
  'app_service.lang.fil': 'الفلبينية',
  'app_service.theme': 'السمة',
  'app_service.color_theme': 'سمة الألوان',
  'app_service.dark_mode': 'الوضع الداكن',
  'app_service.sys_lang': 'لغة النظام',
  'app_service.select_theme': 'اختيار السمة',
};
