/// 白俄罗斯语
Map<String, String> be = {
  'app_service.language_tag': 'Мовны знак',
  'app_service.:': ':',
  'app_service.settings': 'Налады',
  'app_service.close': 'Закрыць',
  'app_service.lang': 'Мова',
  'app_service.lang.zh': 'Кітайская',
  'app_service.lang.zh_Hans': 'Кітайская (спрошчаная)',
  'app_service.lang.zh-MO': 'Кітайская (Макаа)',
  'app_service.lang.zh-HK': 'Кітайская (Ганконг)',
  'app_service.lang.zh-TW': 'Кітайская (Тайвань)',
  'app_service.lang.en': 'Англійская',
  'app_service.lang.en-US': 'Англійская (US)',
  'app_service.lang.en-GB': 'Англійская (UK)',
  'app_service.lang.fr': 'Французская',
  'app_service.lang.de': 'Нямецкая',
  'app_service.lang.de-DE': 'Нямецкая (Германія)',
  'app_service.lang.it': 'Італьянская',
  'app_service.lang.he': 'Іўрыт',
  'app_service.lang.ar': 'Арабская',
  'app_service.lang.ru': 'Руская',
  'app_service.lang.ru-RU': 'Руская (Расія)',
  'app_service.lang.ru-BY': 'Руская (Беларусь)',
  'app_service.lang.ru-KZ': 'Руская (Казахстан)',
  'app_service.lang.ru-UA': 'Руская (Украіна)',
  'app_service.lang.uk': 'Украінская',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Казахская',
  'app_service.lang.sr': 'Сербская',
  'app_service.lang.ja': 'Японская',
  'app_service.lang.ko': 'Карэйская',
  'app_service.lang.pt': 'Партугальская',
  'app_service.lang.nl': 'Нідэрландская',
  'app_service.lang.tr': 'Турэцкая',
  'app_service.lang.th': 'Тайская',
  'app_service.lang.vi': 'В’етнамская',
  'app_service.lang.ms': 'Малайзійская',
  'app_service.lang.pl': 'Польская',
  'app_service.lang.da': 'Дацкая',
  'app_service.lang.fi': 'Фінская',
  'app_service.lang.la': 'Лацінская',
  'app_service.lang.no': 'Нарвежская',
  'app_service.lang.sk': 'Славацкая',
  'app_service.lang.bg': 'Балгарская',
  'app_service.lang.fil': 'Філіпінская',
  'app_service.theme': 'Тэма',
  'app_service.color_theme': 'Каляровая тэма',
  'app_service.dark_mode': 'Цёмны рэжым',
  'app_service.sys_lang': 'Мова сістэмы',
  'app_service.select_theme': 'Выбраць тэму',
};
