/// 白俄罗斯语
Map<String, String> be = {
  'app_service.language': 'Мова',
  'app_service.languages': 'Мовы',
  'app_service.select_language': 'Выберыце мову',
  'app_service.language_tag': 'Мовны знак',
  'app_service.:': ':',
  'app_service.settings': 'Налады',
  'app_service.close': 'Закрыць',
  'app_service.lang': 'Мова',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Тэма',
  'app_service.color_theme': 'Каляровая тэма',
  'app_service.dark_mode': 'Цёмны рэжым',
  'app_service.sys_lang': 'Мова сістэмы',
  'app_service.select_theme': 'Выбраць тэму',
  'app_service.follow_system': 'Следуйце за сістэмай',
  // theme
  'aquaBlue': 'водацвет',
  'bahamaTrinidad': 'Багамы і Трынідад',
  'barossa': 'Бароса',
  'amberBlue': 'бурштывы колер',
  'bigStoneTulip': 'вялікі камень тюльпан',
  'blueDelight': 'сіні радасць',
  'blueStoneTeal': 'сіні камень чай',
  'blueWhale': 'сіня валь',
  'blumine': 'блюмін',
  'brandBlue': 'брэнд сіні',
  'brownOrange': 'карычнева-апельсінавы',
  'camaroneGreen': 'Камарон зялёны',
  'damaskLunar': 'дамаск месячнае сьвятло',
  'deepBlueSea': 'глыбокія моры сіні',
  'deepPurple': 'глыбокія пурпурны',
  'dellGenoaGreen': 'Дэлл Джэноа зялёны',
  'ebonyClay': 'эбані клей',
  'eggplantPurple': 'баклажан пурпурны',
  'endeavourBlue': 'сіні настаўнічы',
  'espressoCrema': 'эспрэса кавовы крэм',
  'flutterDash': 'флутэр дэш',
  'goldSunset': 'залаты закат',
  'greens': 'зялёны',
  'greenForest': 'зялены лес',
  'greenJungle': 'зялены джунглі',
  'greenMoney': 'зяленыя грошы',
  'greyLaw': 'шэры закон',
  'hippieBlue': 'хіпі сіні',
  'indigoNight': 'індыга ноч',
  'indigoSanMarino': 'Сан-Марына індыга',
  'lipstickPink': 'ружавая помада',
  'mallardValencia': 'Маўленка Валенсія',
  'mangoMojito': 'мангавы махіто',
  'material3': 'матэрыял 3',
  'material3HighContrast': 'матэрыял 3 высокі кантраст',
  'material3Purple': 'матэрыял 3 пурпурны',
  'midnight': 'паўнач',
  'mosqueCyan': 'мечеть галубы',
  'ohMandyRed': 'ага, Мэндзі, чырвоны',
  'outerSpace': 'за межамі космасу',
  'pinkSakura': 'ружавыя сакура',
  'purpleBrown': 'пурпурна-карычневы',
  'redBlue': 'чырвона-сіні',
  'redTornado': 'чырвоны тарнада',
  'redWine': 'чырвонае віно',
  'rosewood': 'розавы дрэва',
  'rustDeepOrange': 'рыжавы глыбокі апельсін',
  'sanJuanBlue': 'Сан-Хуан сіні',
  'sharkOrange': 'акула апельсін',
  'thunderbirdRed': 'Тандэрберд чырвоны',
  'verdunGreen': 'Верден зялёны',
  'verdunLime': 'Верден лайм',
  'vesuviusBurned': 'Весувія згарэла',
  'willowWasabi': 'віловае лоза васабі',
  'yukonGoldYellow': 'Юкон золата жоўты',
};
