/// 德语
Map<String, String> de = {
  'app_service.language_tag': 'Sprachetikett',
  'app_service.:': ':',
  'app_service.settings': 'Einstellungen',
  'app_service.close': 'Schließen',
  'app_service.lang': 'Sprache',
  'app_service.lang.zh': 'Chinesisch',
  'app_service.lang.zh_Hans': 'Chinesisch (vereinf)',
  'app_service.lang.zh-MO': 'Chinesisch (Macao)',
  'app_service.lang.zh-HK': 'Chinesisch (Hongkong)',
  'app_service.lang.zh-TW': 'Chinesisch (Taiwan)',
  'app_service.lang.en': 'Englisch',
  'app_service.lang.en-US': 'Englisch (US)',
  'app_service.lang.en-GB': 'Englisch (UK)',
  'app_service.lang.fr': 'Französisch',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italienisch',
  'app_service.lang.he': 'Hebräisch',
  'app_service.lang.ar': 'Arabisch',
  'app_service.lang.ru': 'Russisch',
  'app_service.lang.ru-RU': 'Russisch (Russland)',
  'app_service.lang.ru-BY': 'Russisch (Weißrussland)',
  'app_service.lang.ru-KZ': 'Russisch (Kasachstan)',
  'app_service.lang.ru-UA': 'Russisch (Ukraine)',
  'app_service.lang.uk': 'Ukrainisch',
  'app_service.lang.be': 'Weißrussisch',
  'app_service.lang.kk': 'Kasachisch',
  'app_service.lang.sr': 'Serbisch',
  'app_service.lang.ja': 'Japanisch',
  'app_service.lang.ko': 'Koreanisch',
  'app_service.lang.pt': 'Portugiesisch',
  'app_service.lang.nl': 'Niederländisch',
  'app_service.lang.tr': 'Türkisch',
  'app_service.lang.th': 'Thailändisch',
  'app_service.lang.vi': 'Vietnamesisch',
  'app_service.lang.ms': 'Malaiisch',
  'app_service.lang.pl': 'Polnisch',
  'app_service.lang.da': 'Dänisch',
  'app_service.lang.fi': 'Finnisch',
  'app_service.lang.la': 'Lateinisch',
  'app_service.lang.no': 'Norwegisch',
  'app_service.lang.sk': 'Slowakisch',
  'app_service.lang.bg': 'Bulgarisch',
  'app_service.lang.fil': 'Filipino',
  'app_service.theme': 'Thema',
  'app_service.color_theme': 'Farbthema',
  'app_service.dark_mode': 'Dunkelmodus',
  'app_service.sys_lang': 'Systemsprache',
  'app_service.select_theme': 'Thema auswählen',
};
