/// 英语（通用）
Map<String, String> en = {
  'app_service.language': 'Language',
  'app_service.languages': 'Languages',
  'app_service.select_language': 'Select Language',
  'app_service.language_tag': 'Language Tag',
  'app_service.:': ':',
  'app_service.settings': 'Settings',
  'app_service.close': 'Close',
  'app_service.lang': 'Language',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Theme',
  'app_service.color_theme': 'Color Theme',
  'app_service.dark_mode': 'Dark Mode',
  'app_service.sys_lang': 'System Language',
  'app_service.select_theme': 'Select Theme',
  'aquaBlue': 'Aqua Blue',
  // themes
  'bahamaTrinidad': 'Bahama Trinidad',
  'barossa': 'Barossa',
  'amberBlue': 'Amber Blue',
  'bigStoneTulip': 'Big Stone Tulip',
  'blueDelight': 'Blue Delight',
  'blueStoneTeal': 'Blue Stone Teal',
  'blueWhale': 'Blue Whale',
  'blumine': 'Blumine',
  'brandBlue': 'Brand Blue',
  'brownOrange': 'Brown Orange',
  'camaroneGreen': 'Camarone Green',
  'damaskLunar': 'Damask Lunar',
  'deepBlueSea': 'Deep Blue Sea',
  'deepPurple': 'Deep Purple',
  'dellGenoaGreen': 'Dell Genoa Green',
  'ebonyClay': 'Ebony Clay',
  'eggplantPurple': 'Eggplant Purple',
  'endeavourBlue': 'Endeavour Blue',
  'espressoCrema': 'Espresso Crema',
  'flutterDash': 'Flutter Dash',
  'goldSunset': 'Gold Sunset',
  'greens': 'Greens',
  'greenForest': 'Green Forest',
  'greenJungle': 'Green Jungle',
  'greenMoney': 'Green Money',
  'greyLaw': 'Grey Law',
  'hippieBlue': 'Hippie Blue',
  'indigoNight': 'Indigo Night',
  'indigoSanMarino': 'Indigo San Marino',
  'lipstickPink': 'Lipstick Pink',
  'mallardValencia': 'Mallard Valencia',
  'mangoMojito': 'Mango Mojito',
  'material3': 'Material 3',
  'material3HighContrast': 'Material 3 High Contrast',
  'material3Purple': 'Material 3 Purple',
  'midnight': 'Midnight',
  'mosqueCyan': 'Mosque Cyan',
  'ohMandyRed': 'Oh Mandy Red',
  'outerSpace': 'Outer Space',
  'pinkSakura': 'Pink Sakura',
  'purpleBrown': 'Purple Brown',
  'redBlue': 'Red Blue',
  'redTornado': 'Red Tornado',
  'redWine': 'Red Wine',
  'rosewood': 'Rosewood',
  'rustDeepOrange': 'Rust Deep Orange',
  'sanJuanBlue': 'San Juan Blue',
  'sharkOrange': 'Shark Orange',
  'thunderbirdRed': 'Thunderbird Red',
  'verdunGreen': 'Verdun Green',
  'verdunLime': 'Verdun Lime',
  'vesuviusBurned': 'Vesuvius Burned',
  'willowWasabi': 'Willow Wasabi',
  'yukonGoldYellow': 'Yukon Gold Yellow',
};
