/// 英语（通用）
Map<String, String> en = {
  'app_service.language_tag': 'Language Tag',
  'app_service.:': ':',
  'app_service.settings': 'Settings',
  'app_service.close': 'Close',
  'app_service.lang': 'Language',
  'app_service.lang.zh': 'Chinese',
  'app_service.lang.zh_Hans': 'Chinese (Simplified)',
  'app_service.lang.zh-MO': 'Chinese (Macao)',
  'app_service.lang.zh-HK': 'Chinese (HK)',
  'app_service.lang.zh-TW': 'Chinese (Taiwan)',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'French',
  'app_service.lang.de': 'German',
  'app_service.lang.de-DE': 'German (Germany)',
  'app_service.lang.it': 'Italian',
  'app_service.lang.he': 'Hebrew',
  'app_service.lang.ar': 'Arabic',
  'app_service.lang.ru': 'Russian',
  'app_service.lang.ru-RU': 'Russian (Russia)',
  'app_service.lang.ru-BY': 'Russian (Belarus)',
  'app_service.lang.ru-KZ': 'Russian (Kazakhstan)',
  'app_service.lang.ru-UA': 'Russian (Ukraine)',
  'app_service.lang.uk': 'Ukrainian',
  'app_service.lang.be': 'Belarusian',
  'app_service.lang.kk': 'Kazakh',
  'app_service.lang.sr': 'Serbian',
  'app_service.lang.ja': 'Japanese',
  'app_service.lang.ko': 'Korean',
  'app_service.lang.pt': 'Portuguese',
  'app_service.lang.nl': 'Dutch',
  'app_service.lang.tr': 'Turkish',
  'app_service.lang.th': 'Thai',
  'app_service.lang.vi': 'Vietnamese',
  'app_service.lang.ms': 'Malay',
  'app_service.lang.pl': 'Polish',
  'app_service.lang.da': 'Danish',
  'app_service.lang.fi': 'Finnish',
  'app_service.lang.la': 'Latin',
  'app_service.lang.no': 'Norwegian',
  'app_service.lang.sk': 'Slovak',
  'app_service.lang.bg': 'Bulgarian',
  'app_service.lang.fil': 'Filipino',
  'app_service.theme': 'Theme',
  'app_service.color_theme': 'Color Theme',
  'app_service.dark_mode': 'Dark Mode',
  'app_service.sys_lang': 'System Language',
  'app_service.select_theme': 'Select Theme',
};
