/// 法语
Map<String, String> fr = {
  'app_service.language_tag': 'Étiquette de langue',
  'app_service.:': ' : ',
  'app_service.settings': 'Paramètres',
  'app_service.close': 'Fermer',
  'app_service.lang': 'Langue',
  'app_service.lang.zh': 'Chinois',
  'app_service.lang.zh_Hans': 'Chinois (simpl)',
  'app_service.lang.zh-MO': 'Chinois (Macao)',
  'app_service.lang.zh-HK': 'Chinois (Hong Kong)',
  'app_service.lang.zh-TW': 'Chinois (Taïwan)',
  'app_service.lang.en': 'Anglais',
  'app_service.lang.en-US': 'Anglais (US)',
  'app_service.lang.en-GB': 'Anglais (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Allemand',
  'app_service.lang.de-DE': 'Allemand (Allemagne)',
  'app_service.lang.it': 'Italien',
  'app_service.lang.he': 'Hébreu',
  'app_service.lang.ar': 'Arabe',
  'app_service.lang.ru': 'Russe',
  'app_service.lang.ru-RU': 'Russe (Russie)',
  'app_service.lang.ru-BY': 'Russe (Biélorussie)',
  'app_service.lang.ru-KZ': 'Russe (Kazakhstan)',
  'app_service.lang.ru-UA': 'Russe (Ukraine)',
  'app_service.lang.uk': 'Ukrainien',
  'app_service.lang.be': 'Biélorusse',
  'app_service.lang.kk': 'Kazakh',
  'app_service.lang.sr': 'Serbe',
  'app_service.lang.ja': 'Japonais',
  'app_service.lang.ko': 'Coréen',
  'app_service.lang.pt': 'Portugais',
  'app_service.lang.nl': 'Néerlandais',
  'app_service.lang.tr': 'Turc',
  'app_service.lang.th': 'Thaï',
  'app_service.lang.vi': 'Vietnamien',
  'app_service.lang.ms': 'Malais',
  'app_service.lang.pl': 'Polonais',
  'app_service.lang.da': 'Danois',
  'app_service.lang.fi': 'Finnois',
  'app_service.lang.la': 'Latin',
  'app_service.lang.no': 'Norvégien',
  'app_service.lang.sk': 'Slovaque',
  'app_service.lang.bg': 'Bulgare',
  'app_service.lang.fil': 'Philippin',
  'app_service.theme': 'Thème',
  'app_service.color_theme': 'Thème de couleur',
  'app_service.dark_mode': 'Mode sombre',
  'app_service.sys_lang': 'Langue du système',
  'app_service.select_theme': 'Sélectionner un thème',
};
