/// 法语
Map<String, String> fr = {
  'app_service.language': 'Langue',
  'app_service.languages': 'Langues',
  'app_service.select_language': 'Choisir la langue',
  'app_service.language_tag': 'Étiquette de langue',
  'app_service.:': ' : ',
  'app_service.settings': 'Paramètres',
  'app_service.close': 'Fermer',
  'app_service.lang': 'Langue',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Thème',
  'app_service.color_theme': 'Thème de couleur',
  'app_service.dark_mode': 'Mode sombre',
  'app_service.sys_lang': 'Langue du système',
  'app_service.select_theme': 'Sélectionner un thème',
  // theme
  'aquaBlue': 'Aquablau',
  'bahamaTrinidad': 'Bahamas Trinidad',
  'barossa': 'Barossa',
  'amberBlue': 'Bernsteinblau',
  'bigStoneTulip': 'Großer Stein Tulpe',
  'blueDelight': 'Blaue Freude',
  'blueStoneTeal': 'Blauer Stein Türkis',
  'blueWhale': 'Blaue Wal',
  'blumine': 'Blumine',
  'brandBlue': 'Markenblau',
  'brownOrange': 'Braunorange',
  'camaroneGreen': 'Kamarongrün',
  'damaskLunar': 'Damaskus Lunar',
  'deepBlueSea': 'Tiefblau Meer',
  'deepPurple': 'Tiefviolett',
  'dellGenoaGreen': 'Dell Genua Grün',
  'ebonyClay': 'Ebenholz Lehm',
  'eggplantPurple': 'Aubergine Violett',
  'endeavourBlue': 'Unternehmungslustiges Blau',
  'espressoCrema': 'Espresso Creme',
  'flutterDash': 'Flattern Sprint',
  'goldSunset': 'Goldener Sonnenuntergang',
  'greens': 'Grüns',
  'greenForest': 'Grüner Wald',
  'greenJungle': 'Grüner Dschungel',
  'greenMoney': 'Grünes Geld',
  'greyLaw': 'Graues Gesetz',
  'hippieBlue': 'Hippieblau',
  'indigoNight': 'Indigoblau Nacht',
  'indigoSanMarino': 'Indigo San Marino',
  'lipstickPink': 'Lippenstiftrosa',
  'mallardValencia': 'Mallard Valencia',
  'mangoMojito': 'Mango-Mojito',
  'material3': 'Material 3',
  'material3HighContrast': 'Material 3 Hoher Kontrast',
  'material3Purple': 'Material 3 Violett',
  'midnight': 'Mitternacht',
  'mosqueCyan': 'Moschee Cyan',
  'ohMandyRed': 'Oh Mandy Rot',
  'outerSpace': 'Weltraum',
  'pinkSakura': 'Pink Sakura',
  'purpleBrown': 'Violettbraun',
  'redBlue': 'Rotblau',
  'redTornado': 'Roter Wirbelsturm',
  'redWine': 'Rotwein',
  'rosewood': 'Palisander',
  'rustDeepOrange': 'Rost Tieforange',
  'sanJuanBlue': 'San Juan Blau',
  'sharkOrange': 'Haiorange',
  'thunderbirdRed': 'Donnervogelrot',
  'verdunGreen': 'Verdungrün',
  'verdunLime': 'Verdunlimette',
  'vesuviusBurned': 'Vesuv Verbrannt',
  'willowWasabi': 'Weiden-Wasabi',
  'yukonGoldYellow': 'Yukon Goldgelb',
};
