/// 中文繁体
Map<String, String> hant = {
  'app_service.language': '語言',
  'app_service.languages': '語言',
  'app_service.select_language': '選擇語言',
  'app_service.language_tag': '語言標籤',
  'app_service.:': '：',
  'app_service.settings': '設置',
  'app_service.close': '關閉',
  'app_service.lang': '語言',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': '主題',
  'app_service.color_theme': '顏色主題',
  'app_service.dark_mode': '暗黑模式',
  'app_service.sys_lang': '系統語言',
  'app_service.select_theme': '選擇主題',
  // 主題
  'aquaBlue': '水藍',
  'bahamaTrinidad': '巴哈馬特立尼達',
  'barossa': '巴羅薩',
  'amberBlue': '琥珀藍',
  'bigStoneTulip': '大石鬱金香',
  'blueDelight': '藍色愉悅',
  'blueStoneTeal': '藍石青',
  'blueWhale': '藍鯨',
  'blumine': '布魯明',
  'brandBlue': '品牌藍',
  'brownOrange': '棕橙',
  'camaroneGreen': '卡馬隆綠',
  'damaskLunar': '大馬士革月光',
  'deepBlueSea': '深海藍',
  'deepPurple': '深紫',
  'dellGenoaGreen': '戴爾熱那亞綠',
  'ebonyClay': '烏木黏土',
  'eggplantPurple': '茄子紫',
  'endeavourBlue': '努力藍',
  'espressoCrema': '濃縮咖啡奶油',
  'flutterDash': '飄揚衝刺',
  'goldSunset': '金色日落',
  'greens': '綠色',
  'greenForest': '綠色森林',
  'greenJungle': '綠色叢林',
  'greenMoney': '金錢綠',
  'greyLaw': '灰色法則',
  'hippieBlue': '嬉皮藍',
  'indigoNight': '靛藍夜',
  'indigoSanMarino': '聖馬力諾靛藍',
  'lipstickPink': '口紅粉',
  'mallardValencia': '瓦倫西亞野鴨',
  'mangoMojito': '芒果莫吉托',
  'material3': '材質3',
  'material3HighContrast': '材質3高對比度',
  'material3Purple': '材質3紫',
  'midnight': '午夜',
  'mosqueCyan': '清真寺青',
  'ohMandyRed': '哦曼迪紅',
  'outerSpace': '外太空',
  'pinkSakura': '粉色櫻花',
  'purpleBrown': '紫棕',
  'redBlue': '紅藍',
  'redTornado': '紅色龍捲風',
  'redWine': '紅酒',
  'rosewood': '紫檀木',
  'rustDeepOrange': '深橙鏽色',
  'sanJuanBlue': '聖胡安藍',
  'sharkOrange': '鯊魚橙',
  'thunderbirdRed': '雷鳥紅',
  'verdunGreen': '凡爾登綠',
  'verdunLime': '凡爾登青檸',
  'vesuviusBurned': '維蘇威火山燒',
  'willowWasabi': '柳葉芥末',
  'yukonGoldYellow': '育空金黃',
};
