/// 中文简体
Map<String, String> hans = {
  'app_service.language': '语言',
  'app_service.languages': '语言',
  'app_service.select_language': '选择语言',
  'app_service.language_tag': '语言标签',
  'app_service.:': '：',
  'app_service.settings': '设置',
  'app_service.close': '关闭',
  'app_service.lang': '语言',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': '主题',
  'app_service.color_theme': '颜色主题',
  'app_service.dark_mode': '暗黑模式',
  'app_service.sys_lang': '系统语言',
  'app_service.select_theme': '选择主题',
  // 主题
  'aquaBlue': '水蓝',
  'bahamaTrinidad': '巴哈马特立尼达',
  'barossa': '巴罗萨',
  'amberBlue': '琥珀蓝',
  'bigStoneTulip': '大石郁金香',
  'blueDelight': '蓝色愉悦',
  'blueStoneTeal': '蓝石青',
  'blueWhale': '蓝鲸',
  'blumine': '布鲁明',
  'brandBlue': '品牌蓝',
  'brownOrange': '棕橙',
  'camaroneGreen': '卡马隆绿',
  'damaskLunar': '大马士革月光',
  'deepBlueSea': '深海蓝',
  'deepPurple': '深紫',
  'dellGenoaGreen': '戴尔热那亚绿',
  'ebonyClay': '乌木黏土',
  'eggplantPurple': '茄子紫',
  'endeavourBlue': '努力蓝',
  'espressoCrema': '浓缩咖啡奶油',
  'flutterDash': '飘扬冲刺',
  'goldSunset': '金色日落',
  'greens': '绿色',
  'greenForest': '绿色森林',
  'greenJungle': '绿色丛林',
  'greenMoney': '金钱绿',
  'greyLaw': '灰色法则',
  'hippieBlue': '嬉皮蓝',
  'indigoNight': '靛蓝夜',
  'indigoSanMarino': '圣马力诺靛蓝',
  'lipstickPink': '口红粉',
  'mallardValencia': '瓦伦西亚野鸭',
  'mangoMojito': '芒果莫吉托',
  'material3': '材质3',
  'material3HighContrast': '材质3高对比度',
  'material3Purple': '材质3紫',
  'midnight': '午夜',
  'mosqueCyan': '清真寺青',
  'ohMandyRed': '哦曼迪红',
  'outerSpace': '外太空',
  'pinkSakura': '粉色樱花',
  'purpleBrown': '紫棕',
  'redBlue': '红蓝',
  'redTornado': '红色龙卷风',
  'redWine': '红酒',
  'rosewood': '紫檀木',
  'rustDeepOrange': '深橙锈色',
  'sanJuanBlue': '圣胡安蓝',
  'sharkOrange': '鲨鱼橙',
  'thunderbirdRed': '雷鸟红',
  'verdunGreen': '凡尔登绿',
  'verdunLime': '凡尔登青柠',
  'vesuviusBurned': '维苏威火山烧',
  'willowWasabi': '柳叶芥末',
  'yukonGoldYellow': '育空金黄',
};
