/// 希伯来语
Map<String, String> he = {
  'app_service.language': 'שפה',
  'app_service.languages': 'שפות',
  'app_service.select_language': 'בחר שפה',
  'app_service.language_tag': 'תג שפה',
  'app_service.:': ':',
  'app_service.settings': 'הגדרות',
  'app_service.close': 'סגור',
  'app_service.lang': 'שפה',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'ערכת נושא',
  'app_service.color_theme': 'ערכת צבעים',
  'app_service.dark_mode': 'מצב אפל',
  'app_service.sys_lang': 'שפת המערכת',
  'app_service.select_theme': 'בחר ערכת נושא',
  'app_service.follow_system': 'עקוב אחר המערכת',
  // theme
  'aquaBlue': 'תכלת מים',
  'bahamaTrinidad': 'בהאמה טרינידד',
  'barossa': 'ברוסה',
  'amberBlue': 'כחול עוגת שומשום',
  'bigStoneTulip': 'טוליפ סטון גדול',
  'blueDelight': 'הנאה כחולה',
  'blueStoneTeal': 'כחול אבן טיל',
  'blueWhale': 'לוויתן כחול',
  'blumine': 'בלומינה',
  'brandBlue': 'כחול מותג',
  'brownOrange': 'חום כתום',
  'camaroneGreen': 'ירוק קמרון',
  'damaskLunar': 'לונר דמשק',
  'deepBlueSea': 'תמונת עמוקה',
  'deepPurple': 'סגול עמוק',
  'dellGenoaGreen': 'ירוק דל גנואה',
  'ebonyClay': 'חול אבן',
  'eggplantPurple': 'סגול בצל',
  'endeavourBlue': 'ניסיון כחול',
  'espressoCrema': 'אספרסו קרמה',
  'flutterDash': 'פרפר מהלך',
  'goldSunset': 'שקיעת זהב',
  'greens': 'ירוקים',
  'greenForest': 'ירוק יער',
  'greenJungle': 'יער ירוק',
  'greenMoney': 'כסף ירוק',
  'greyLaw': 'חוק אפור',
  'hippieBlue': 'היפי כחול',
  'indigoNight': 'לילה אינדיגו',
  'indigoSanMarino': 'סן מרינו אינדיגו',
  'lipstickPink': 'ורוד חומריות',
  'mallardValencia': 'וולנסיה מרארד',
  'mangoMojito': 'מנגו מוהיטו',
  'material3': 'חומר 3',
  'material3HighContrast': 'חומר 3 ניגודיות גבוהה',
  'material3Purple': 'חומר 3 סגול',
  'midnight': 'חצות',
  'mosqueCyan': 'כחול מסגד',
  'ohMandyRed': 'אוה מנדי אדום',
  'outerSpace': 'חלל חיצון',
  'pinkSakura': 'ורוד סאקורה',
  'purpleBrown': 'חום סגול',
  'redBlue': 'אדום כחול',
  'redTornado': 'סופת אדום',
  'redWine': 'יין אדום',
  'rosewood': 'אפריקה מצורף',
  'rustDeepOrange': 'תכלת סדק',
  'sanJuanBlue': 'סן חואן כחול',
  'sharkOrange': 'כתום כריש',
  'thunderbirdRed': 'אדום תנורת',
  'verdunGreen': 'ירוק ורדון',
  'verdunLime': 'ליים ורדון',
  'vesuviusBurned': 'שרוף וסוביוס',
  'willowWasabi': 'ווילו וואסבי',
  'yukonGoldYellow': 'יקון זהב צהוב',
};
