/// 希伯来语
Map<String, String> he = {
  'app_service.language_tag': 'תג שפה',
  'app_service.:': ':',
  'app_service.settings': 'הגדרות',
  'app_service.close': 'סגור',
  'app_service.lang': 'שפה',
  'app_service.lang.zh': 'סינית',
  'app_service.lang.zh_Hans': 'סינית (פשוטה)',
  'app_service.lang.zh-MO': 'סינית (מקאו)',
  'app_service.lang.zh-HK': 'סינית (הונג קונג)',
  'app_service.lang.zh-TW': 'סינית (טיוואן)',
  'app_service.lang.en': 'אנגלית',
  'app_service.lang.en-US': 'אנגלית (ארצות הברית)',
  'app_service.lang.en-GB': 'אנגלית (בריטניה)',
  'app_service.lang.fr': 'צרפתית',
  'app_service.lang.de': 'גרמנית',
  'app_service.lang.de-DE': 'גרמנית (גרמניה)',
  'app_service.lang.it': 'איטלקית',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'ערבית',
  'app_service.lang.ru': 'רוסית',
  'app_service.lang.ru-RU': 'רוסית (רוסיה)',
  'app_service.lang.ru-BY': 'רוסית (בלארוס)',
  'app_service.lang.ru-KZ': 'רוסית (קזחסטן)',
  'app_service.lang.ru-UA': 'רוסית (אוקראינה)',
  'app_service.lang.uk': 'אוקראינית',
  'app_service.lang.be': 'בלרוסית',
  'app_service.lang.kk': 'קזחית',
  'app_service.lang.sr': 'סרבית',
  'app_service.lang.ja': 'יפנית',
  'app_service.lang.ko': 'קוריאנית',
  'app_service.lang.pt': 'פורטוגזית',
  'app_service.lang.nl': 'הולנדית',
  'app_service.lang.tr': 'טורקית',
  'app_service.lang.th': 'תאילנדית',
  'app_service.lang.vi': 'וייטנאמית',
  'app_service.lang.ms': 'מלאית',
  'app_service.lang.pl': 'פולנית',
  'app_service.lang.da': 'דנית',
  'app_service.lang.fi': 'פינית',
  'app_service.lang.la': 'לטינית',
  'app_service.lang.no': 'נורווגית',
  'app_service.lang.sk': 'סלובקית',
  'app_service.lang.bg': 'בולגרית',
  'app_service.lang.fil': 'פיליפינית',
  'app_service.theme': 'ערכת נושא',
  'app_service.color_theme': 'ערכת צבעים',
  'app_service.dark_mode': 'מצב אפל',
  'app_service.sys_lang': 'שפת המערכת',
  'app_service.select_theme': 'בחר ערכת נושא',
};
