/// 意大利语
Map<String, String> it = {
  'app_service.language': 'Lingua',
  'app_service.languages': 'Lingue',
  'app_service.select_language': 'Seleziona la lingua',
  'app_service.language_tag': 'Etichetta linguistica',
  'app_service.:': ':',
  'app_service.settings': 'Impostazioni',
  'app_service.close': 'Chiudi',
  'app_service.lang': 'Lingua',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Tema',
  'app_service.color_theme': 'Tema colore',
  'app_service.dark_mode': 'Modalità scura',
  'app_service.sys_lang': 'Lingua di sistema',
  'app_service.select_theme': 'Seleziona tema',
  'app_service.follow_system': 'Segui il sistema',
  // theme
  'aquaBlue': 'Azzurro acqua',
  'bahamaTrinidad': 'Bahama Trinidad',
  'barossa': 'Barossa',
  'amberBlue': 'Ambra Blu',
  'bigStoneTulip': 'Tulipano di pietra grande',
  'blueDelight': 'Delizia blu',
  'blueStoneTeal': 'Teal di pietra blu',
  'blueWhale': 'Balena blu',
  'blumine': 'Blumine',
  'brandBlue': 'Blu del marchio',
  'brownOrange': 'Marrone arancione',
  'camaroneGreen': 'Verde camarone',
  'damaskLunar': 'Lunare damasco',
  'deepBlueSea': 'Blu profondo del mare',
  'deepPurple': 'Porpora profonda',
  'dellGenoaGreen': 'Verde Genova di Dell',
  'ebonyClay': 'Argilla di ebano',
  'eggplantPurple': 'Melanzana viola',
  'endeavourBlue': 'Blu impresa',
  'espressoCrema': 'Crema di caffè espresso',
  'flutterDash': 'Flutter Dash',
  'goldSunset': 'Tramonto dorato',
  'greens': 'Verdi',
  'greenForest': 'Foresta verde',
  'greenJungle': 'Giungla verde',
  'greenMoney': 'Verde del denaro',
  'greyLaw': 'Legge grigia',
  'hippieBlue': 'Blu hippie',
  'indigoNight': 'Notte indaco',
  'indigoSanMarino': 'San Marino indaco',
  'lipstickPink': 'Rosa rossetto',
  'mallardValencia': 'Mallard Valencia',
  'mangoMojito': 'Mango Mojito',
  'material3': 'Materiale 3',
  'material3HighContrast': 'Alto contrasto del materiale 3',
  'material3Purple': 'Materiale 3 Viola',
  'midnight': 'Mezzanotte',
  'mosqueCyan': 'Ciano della moschea',
  'ohMandyRed': 'Oh Mandy Rosso',
  'outerSpace': 'Spazio esterno',
  'pinkSakura': 'Sakura rosa',
  'purpleBrown': 'Marrone viola',
  'redBlue': 'Rosso blu',
  'redTornado': 'Tornado rosso',
  'redWine': 'Vino rosso',
  'rosewood': 'Legno di rosa',
  'rustDeepOrange': 'Arancione profondo di ruggine',
  'sanJuanBlue': 'Blu di San Juan',
  'sharkOrange': 'Arancione squalo',
  'thunderbirdRed': 'Rosso del tuono',
  'verdunGreen': 'Verde di Verdun',
  'verdunLime': 'Lime di Verdun',
  'vesuviusBurned': 'Vesuvio bruciato',
  'willowWasabi': 'Salice Wasabi',
  'yukonGoldYellow': 'Giallo oro dello Yukon',
};
