/// 意大利语
Map<String, String> it = {
  'app_service.language_tag': 'Etichetta linguistica',
  'app_service.:': ':',
  'app_service.settings': 'Impostazioni',
  'app_service.close': 'Chiudi',
  'app_service.lang': 'Lingua',
  'app_service.lang.zh': 'Cinese',
  'app_service.lang.zh_Hans': 'Cinese (semplificato)',
  'app_service.lang.zh-MO': 'Cinese (Macao)',
  'app_service.lang.zh-HK': 'Cinese (Hong Kong)',
  'app_service.lang.zh-TW': 'Cinese (Taiwan)',
  'app_service.lang.en': 'Inglese',
  'app_service.lang.en-US': 'Inglese (Stati Uniti)',
  'app_service.lang.en-GB': 'Inglese (Regno Unito)',
  'app_service.lang.fr': 'Francese',
  'app_service.lang.de': 'Tedesco',
  'app_service.lang.de-DE': 'Tedesco (Germania)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'Ebraico',
  'app_service.lang.ar': 'Arabo',
  'app_service.lang.ru': 'Russo',
  'app_service.lang.ru-RU': 'Russo (Russia)',
  'app_service.lang.ru-BY': 'Russo (Bielorussia)',
  'app_service.lang.ru-KZ': 'Russo (Kazakistan)',
  'app_service.lang.ru-UA': 'Russo (Ucraina)',
  'app_service.lang.uk': 'Ucraino',
  'app_service.lang.be': 'Bielorusso',
  'app_service.lang.kk': 'Kazako',
  'app_service.lang.sr': 'Serbo',
  'app_service.lang.ja': 'Giapponese',
  'app_service.lang.ko': 'Coreano',
  'app_service.lang.pt': 'Portoghese',
  'app_service.lang.nl': 'Olandese',
  'app_service.lang.tr': 'Turco',
  'app_service.lang.th': 'Tailandese',
  'app_service.lang.vi': 'Vietnamita',
  'app_service.lang.ms': 'Malese',
  'app_service.lang.pl': 'Polacco',
  'app_service.lang.da': 'Danese',
  'app_service.lang.fi': 'Finlandese',
  'app_service.lang.la': 'Latino',
  'app_service.lang.no': 'Norvegese',
  'app_service.lang.sk': 'Slovacco',
  'app_service.lang.bg': 'Bulgaro',
  'app_service.lang.fil': 'Filippino',
  'app_service.theme': 'Tema',
  'app_service.color_theme': 'Tema colore',
  'app_service.dark_mode': 'Modalità scura',
  'app_service.sys_lang': 'Lingua di sistema',
  'app_service.select_theme': 'Seleziona tema',
};
