/// 日语
Map<String, String> ja = {
  'app_service.language': '言語',
  'app_service.languages': '言語',
  'app_service.select_language': '言語を選択',
  'app_service.language_tag': '言語ラベル',
  'app_service.:': '：',
  'app_service.settings': '設定',
  'app_service.close': '閉じる',
  'app_service.lang': '言語',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'テーマ',
  'app_service.color_theme': 'カラーテーマ',
  'app_service.dark_mode': 'ダークモード',
  'app_service.sys_lang': 'システム言語',
  'app_service.select_theme': 'テーマの選択',
  // 主题
  "aquaBlue": "アクアブルー",
  "bahamaTrinidad": "バハマトリニダード",
  "barossa": "バロッサ",
  "amberBlue": "琥珀ブルー",
  "bigStoneTulip": "ビッグストーンチューリップ",
  "blueDelight": "ブルーディライト",
  "blueStoneTeal": "ブルーストーンティール",
  "blueWhale": "青いクジラ",
  "blumine": "ブルミネ",
  "brandBlue": "ブランドブルー",
  "brownOrange": "茶色オレンジ",
  "camaroneGreen": "カマロングリーン",
  "damaskLunar": "ダマスクルナ",
  "deepBlueSea": "深い青い海",
  "deepPurple": "深紫",
  "dellGenoaGreen": "デルジェノヴァグリーン",
  "ebonyClay": "エボニークレイ",
  "eggplantPurple": "ナス紫",
  "endeavourBlue": "エンデバーブルー",
  "espressoCrema": "エスプレッソクレマ",
  "flutterDash": "フラッターダッシュ",
  "goldSunset": "ゴールドサンセット",
  "greens": "グリーン",
  "greenForest": "緑の森",
  "greenJungle": "緑のジャングル",
  "greenMoney": "緑のお金",
  "greyLaw": "グレーロー",
  "hippieBlue": "ヒッピーのブルー",
  "indigoNight": "インディゴナイト",
  "indigoSanMarino": "インディゴサンマリノ",
  "lipstickPink": "口紅ピンク",
  "mallardValencia": "マラードバレンシア",
  "mangoMojito": "マンゴーモヒート",
  "material3": "素材3",
  "material3HighContrast": "素材3ハイコントラスト",
  "material3Purple": "素材3パープル",
  "midnight": "真夜中",
  "mosqueCyan": "モスクシアン",
  "ohMandyRed": "オーマンディレッド",
  "outerSpace": "外宇宙",
  "pinkSakura": "ピンクサクラ",
  "purpleBrown": "紫茶色",
  "redBlue": "赤青",
  "redTornado": "赤い竜巻",
  "redWine": "赤ワイン",
  "rosewood": "紫檀",
  "rustDeepOrange": "さび深いオレンジ",
  "sanJuanBlue": "サンフアンブルー",
  "sharkOrange": "サメオレンジ",
  "thunderbirdRed": "サンダーバードレッド",
  "verdunGreen": "ヴェルダングリーン",
  "verdunLime": "ヴェルダンライム",
  "vesuviusBurned": "ヴェスヴィオ焼け",
  "willowWasabi": "ウィローワサビ",
  "yukonGoldYellow": "ユーコンゴールドイエロー",
};
