/// 哈萨克语语
Map<String, String> kk = {
  'app_service.language_tag': 'Тіл тақтауы',
  'app_service.:': ':',
  'app_service.settings': 'Параметрлер',
  'app_service.close': 'Жабу',
  'app_service.lang': 'Тіл',
  'app_service.lang.zh': 'Қытай тілі',
  'app_service.lang.zh_Hans': 'Қытай тілі (жалпылаулы)',
  'app_service.lang.zh-MO': 'Қытай тілі (Макао)',
  'app_service.lang.zh-HK': 'Қытай тілі (Гонконг)',
  'app_service.lang.zh-TW': 'Қытай тілі (Тайвань)',
  'app_service.lang.en': 'Ағылшын тілі',
  'app_service.lang.en-US': 'Ағылшын тілі (US)',
  'app_service.lang.en-GB': 'Ағылшын тілі (UK)',
  'app_service.lang.fr': 'Француз тілі',
  'app_service.lang.de': 'Неміс тілі',
  'app_service.lang.de-DE': 'Неміс тілі (Германия)',
  'app_service.lang.it': 'Италія тілі',
  'app_service.lang.he': 'Иврит тілі',
  'app_service.lang.ar': 'Араб тілі',
  'app_service.lang.ru': 'Орыс тілі',
  'app_service.lang.ru-RU': 'Орыс тілі (Ресей)',
  'app_service.lang.ru-BY': 'Орыс тілі (Беларусь)',
  'app_service.lang.ru-KZ': 'Орыс тілі (Қазақстан)',
  'app_service.lang.ru-UA': 'Орыс тілі (Украина)',
  'app_service.lang.uk': 'Украин тілі',
  'app_service.lang.be': 'Беларусь тілі',
  'app_service.lang.kk': 'Қазақ тілі',
  'app_service.lang.sr': 'Серб тілі',
  'app_service.lang.ja': 'Жапон тілі',
  'app_service.lang.ko': 'Корей тілі',
  'app_service.lang.pt': 'Португал тілі',
  'app_service.lang.nl': 'Нидерланд тілі',
  'app_service.lang.tr': 'Түрік тілі',
  'app_service.lang.th': 'Тай тілі',
  'app_service.lang.vi': 'Вьетнам тілі',
  'app_service.lang.ms': 'Малай тілі',
  'app_service.lang.pl': 'Поляк тілі',
  'app_service.lang.da': 'Дат тілі',
  'app_service.lang.fi': 'Фин тілі',
  'app_service.lang.la': 'Латын тілі',
  'app_service.lang.no': 'Норвег тілі',
  'app_service.lang.sk': 'Словак тілі',
  'app_service.lang.bg': 'Болгар тілі',
  'app_service.lang.fil': 'Филиппин тілі',
  'app_service.theme': 'Тақырып',
  'app_service.color_theme': 'Түс тақырыбы',
  'app_service.dark_mode': 'Қара көз режимі',
  'app_service.sys_lang': 'Жүйелік тіл',
  'app_service.select_theme': 'Тақырыпты таңдау',
};
