/// 哈萨克语
Map<String, String> kk = {
  'app_service.language': 'Тіл',
  'app_service.languages': 'Тілдер',
  'app_service.select_language': 'Тілді таңдаңыз',
  'app_service.language_tag': 'Тіл тақтауы',
  'app_service.:': ':',
  'app_service.settings': 'Параметрлер',
  'app_service.close': 'Жабу',
  'app_service.lang': 'Тіл',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Тақырып',
  'app_service.color_theme': 'Түс тақырыбы',
  'app_service.dark_mode': 'Қара көз режимі',
  'app_service.sys_lang': 'Жүйелік тіл',
  'app_service.select_theme': 'Тақырыпты таңдау',
  // theme
  'aquaBlue': 'су жасыл',
  'bahamaTrinidad': 'Багама Тринидад',
  'barossa': 'Баросса',
  'amberBlue': 'көк күлгін',
  'bigStoneTulip': 'үлкен тас лалек',
  'blueDelight': 'көк қуаныш',
  'blueStoneTeal': 'көк тас тынық',
  'blueWhale': 'көк кит',
  'blumine': 'блумин',
  'brandBlue': 'бренд көк',
  'brownOrange': 'қоңыр қызыл',
  'camaroneGreen': 'камарон жасыл',
  'damaskLunar': 'дамаск айқұрау',
  'deepBlueSea': 'кемең көк теңіз',
  'deepPurple': 'кемең күлгін',
  'dellGenoaGreen': 'дель Женуя жасыл',
  'ebonyClay': 'тас шаңырау',
  'eggplantPurple': 'баклажан күлгін',
  'endeavourBlue': 'меттік көк',
  'espressoCrema': 'эспрессо крем',
  'flutterDash': 'судалу атасу',
  'goldSunset': 'алтын күн батысы',
  'greens': 'жасылдар',
  'greenForest': 'жасыл орман',
  'greenJungle': 'жасыл арғы',
  'greenMoney': 'ақша жасыл',
  'greyLaw': 'күлігі күлігі',
  'hippieBlue': 'хиппи көк',
  'indigoNight': 'индиго кеш',
  'indigoSanMarino': 'Сан Марино индиго',
  'lipstickPink': 'данақ қызыл',
  'mallardValencia': 'малард Валенсия',
  'mangoMojito': 'манго мохито',
  'material3': 'материал 3',
  'material3HighContrast': 'материал 3 жоғары контраст',
  'material3Purple': 'материал 3 күлгін',
  'midnight': 'түн жақсы',
  'mosqueCyan': 'мешіт көк',
  'ohMandyRed': 'О, Мэнди қызыл',
  'outerSpace': 'сыртқы кеңістік',
  'pinkSakura': 'қызыл сакура',
  'purpleBrown': 'күлгін кқауын',
  'redBlue': 'қызыл көк',
  'redTornado': 'қызыл торнадо',
  'redWine': 'қызыл шарап',
  'rosewood': 'құлпынай',
  'rustDeepOrange': 'күрініс кішкене кірмізі',
  'sanJuanBlue': 'Сан-Хуан көк',
  'sharkOrange': 'көмбе кірмізі',
  'thunderbirdRed': 'ауыр қызыл',
  'verdunGreen': 'Верден жасыл',
  'verdunLime': 'Верден лайм',
  'vesuviusBurned': 'Везувий жанып түкті',
  'willowWasabi': 'сабақ абыржуазы',
  'yukonGoldYellow': 'Юкон алтын сары',
};
