/// 韩语
Map<String, String> ko = {
  'app_service.language': '언어',
  'app_service.languages': '언어',
  'app_service.select_language': '언어 선택',
  'app_service.language_tag': '언어 레이블',
  'app_service.:': ':',
  'app_service.settings': '설정',
  'app_service.close': '닫기',
  'app_service.lang': '언어',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': '테마',
  'app_service.color_theme': '색상 테마',
  'app_service.dark_mode': '다크 모드',
  'app_service.sys_lang': '시스템 언어',
  'app_service.select_theme': '테마 선택',
  // themes
  'aquaBlue': '아쿠아 블루',
  'bahamaTrinidad': '바하마 트리니다드',
  'barossa': '바로사',
  'amberBlue': '호박 블루',
  'bigStoneTulip': '큰 돌 튤립',
  'blueDelight': '파란색 기쁨',
  'blueStoneTeal': '파란 돌색',
  'blueWhale': '푸른 고래',
  'blumine': '블루민',
  'brandBlue': '브랜드 블루',
  'brownOrange': '갈색 오렌지',
  'camaroneGreen': '카마론 그린',
  'damaskLunar': '대마스크 월광',
  'deepBlueSea': '깊은 바다 파랑',
  'deepPurple': '진보라',
  'dellGenoaGreen': '델 제노아 그린',
  'ebonyClay': '흑단 점토',
  'eggplantPurple': '가지 보라',
  'endeavourBlue': '노력 블루',
  'espressoCrema': '에스프레소 크레마',
  'flutterDash': '플러터 대쉬',
  'goldSunset': '금빛 일몰',
  'greens': '초록색',
  'greenForest': '초록 숲',
  'greenJungle': '초록 밀림',
  'greenMoney': '돈 초록',
  'greyLaw': '회색 법칙',
  'hippieBlue': '히피 블루',
  'indigoNight': '인디고 밤',
  'indigoSanMarino': '산 마리노 인디고',
  'lipstickPink': '립스틱 핑크',
  'mallardValencia': '오리 발렌시아',
  'mangoMojito': '망고 모히또',
  'material3': '재료3',
  'material3HighContrast': '재료3 고대비',
  'material3Purple': '재료3 보라',
  'midnight': '자정',
  'mosqueCyan': '모스크 싸이언',
  'ohMandyRed': '오 만디 레드',
  'outerSpace': '외부 우주',
  'pinkSakura': '핑크 사쿠라',
  'purpleBrown': '보라 갈색',
  'redBlue': '빨강 파랑',
  'redTornado': '붉은색 토네이도',
  'redWine': '레드 와인',
  'rosewood': '장작나무',
  'rustDeepOrange': '녹슨 깊은 주황색',
  'sanJuanBlue': '산 후안 블루',
  'sharkOrange': '상어 오렌지',
  'thunderbirdRed': '천둥새 레드',
  'verdunGreen': '베르당 그린',
  'verdunLime': '베르당 라임',
  'vesuviusBurned': '베수비우스 번트',
  'willowWasabi': '버드나무 와사비',
  'yukonGoldYellow': '유콘 골드 옐로우',
};
