/// 韩语
Map<String, String> ko = {
  'app_service.language_tag': '언어 레이블',
  'app_service.:': ':',
  'app_service.settings': '설정',
  'app_service.close': '닫기',
  'app_service.lang': '언어',
  'app_service.lang.zh': '중국어',
  'app_service.lang.zh_Hans': '중국어 (간체)',
  'app_service.lang.zh-MO': '중국어 (마카오)',
  'app_service.lang.zh-HK': '중국어 (홍콩)',
  'app_service.lang.zh-TW': '중국어 (대만)',
  'app_service.lang.en': '영어',
  'app_service.lang.en-US': '영어 (미국)',
  'app_service.lang.en-GB': '영어 (영국)',
  'app_service.lang.fr': '프랑스어',
  'app_service.lang.de': '독일어',
  'app_service.lang.de-DE': '독일어 (독일)',
  'app_service.lang.it': '이탈리아어',
  'app_service.lang.he': '히브리어',
  'app_service.lang.ar': '아랍어',
  'app_service.lang.ru': '러시아어',
  'app_service.lang.ru-RU': '러시아어 (러시아)',
  'app_service.lang.ru-BY': '러시아어 (벨라루스)',
  'app_service.lang.ru-KZ': '러시아어 (카자흐스탄)',
  'app_service.lang.ru-UA': '러시아어 (우크라이나)',
  'app_service.lang.uk': '우크라이나어',
  'app_service.lang.be': '벨라루시아어',
  'app_service.lang.kk': '카자흐어',
  'app_service.lang.sr': '세르비아어',
  'app_service.lang.ja': '일본어',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': '포르투갈어',
  'app_service.lang.nl': '네덜란드어',
  'app_service.lang.tr': '터키어',
  'app_service.lang.th': '태국어',
  'app_service.lang.vi': '베트남어',
  'app_service.lang.ms': '말레이어',
  'app_service.lang.pl': '폴란드어',
  'app_service.lang.da': '덴마크어',
  'app_service.lang.fi': '핀란드어',
  'app_service.lang.la': '라틴어',
  'app_service.lang.no': '노르웨이어',
  'app_service.lang.sk': '슬로바키아어',
  'app_service.lang.bg': '불가리아어',
  'app_service.lang.fil': '필리핀어',
  'app_service.theme': '테마',
  'app_service.color_theme': '색상 테마',
  'app_service.dark_mode': '다크 모드',
  'app_service.sys_lang': '시스템 언어',
  'app_service.select_theme': '테마 선택',
};
