/// 葡萄牙语
Map<String, String> pt = {
  'app_service.language': 'Língua',
  'app_service.languages': 'Idiomas',
  'app_service.select_language': 'Selecionar idioma',
  'app_service.language_tag': 'Rótulo de Idioma',
  'app_service.:': ':',
  'app_service.settings': 'Configurações',
  'app_service.close': 'Fechar',
  'app_service.lang': 'Idioma',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Tema',
  'app_service.color_theme': 'Tema de cor',
  'app_service.dark_mode': 'Modo escuro',
  'app_service.sys_lang': 'Idioma do sistema',
  'app_service.select_theme': 'Selecionar tema',
  // themes
  'aquaBlue': 'Azul-água',
  'bahamaTrinidad': 'Bahamas Trinidad',
  'barossa': 'Barossa',
  'amberBlue': 'Âmbar Azul',
  'bigStoneTulip': 'Grande Tulipa de Pedra',
  'blueDelight': 'Delícia Azul',
  'blueStoneTeal': 'Azul Pedra Teal',
  'blueWhale': 'Baleia Azul',
  'blumine': 'Blumine',
  'brandBlue': 'Azul da marca',
  'brownOrange': 'Marrom Laranja',
  'camaroneGreen': 'Verde Camarão',
  'damaskLunar': 'Damasco Lunar',
  'deepBlueSea': 'Mar Azul Profundo',
  'deepPurple': 'Roxo Profundo',
  'dellGenoaGreen': 'Verde Genoa Dell',
  'ebonyClay': 'Argila de Ébano',
  'eggplantPurple': 'Beringela Roxa',
  'endeavourBlue': 'Azul Endeavour',
  'espressoCrema': 'Creme de Espresso',
  'flutterDash': 'Flutter Dash',
  'goldSunset': 'Pôr do sol dourado',
  'greens': 'Verdes',
  'greenForest': 'Floresta Verde',
  'greenJungle': 'Selva Verde',
  'greenMoney': 'Dinheiro Verde',
  'greyLaw': 'Lei Cinza',
  'hippieBlue': 'Azul Hippie',
  'indigoNight': 'Noite Índigo',
  'indigoSanMarino': 'Índigo San Marino',
  'lipstickPink': 'Rosa Batom',
  'mallardValencia': 'Mallard Valencia',
  'mangoMojito': 'Mojito de Manga',
  'material3': 'Material 3',
  'material3HighContrast': 'Alto Contraste Material 3',
  'material3Purple': 'Material 3 Roxo',
  'midnight': 'Meia-noite',
  'mosqueCyan': 'Mesquita Ciano',
  'ohMandyRed': 'Oh Mandy Vermelho',
  'outerSpace': 'Espaço Sideral',
  'pinkSakura': 'Sakura Rosa',
  'purpleBrown': 'Marrom Roxo',
  'redBlue': 'Vermelho Azul',
  'redTornado': 'Tornado Vermelho',
  'redWine': 'Vinho Tinto',
  'rosewood': 'Madeira de Rosa',
  'rustDeepOrange': 'Laranja Profundo de Ferrugem',
  'sanJuanBlue': 'Azul de San Juan',
  'sharkOrange': 'Laranja Tubarão',
  'thunderbirdRed': 'Trovão Vermelho',
  'verdunGreen': 'Verde Verdun',
  'verdunLime': 'Limão Verdun',
  'vesuviusBurned': 'Vesúvio Queimado',
  'willowWasabi': 'Salgueiro Wasabi',
  'yukonGoldYellow': 'Amarelo Ouro do Yukon',
};
