/// 葡萄牙语
Map<String, String> pt = {
  'app_service.language_tag': 'Rótulo de Idioma',
  'app_service.:': ':',
  'app_service.settings': 'Configurações',
  'app_service.close': 'Fechar',
  'app_service.lang': 'Idioma',
  'app_service.lang.zh': 'Chinês',
  'app_service.lang.zh_Hans': 'Chinês (Simplificado)',
  'app_service.lang.zh-MO': 'Chinês (Macau)',
  'app_service.lang.zh-HK': 'Chinês (Hong Kong)',
  'app_service.lang.zh-TW': 'Chinês (Taiwan)',
  'app_service.lang.en': 'Inglês',
  'app_service.lang.en-US': 'Inglês (Estados Unidos)',
  'app_service.lang.en-GB': 'Inglês (Reino Unido)',
  'app_service.lang.fr': 'Francês',
  'app_service.lang.de': 'Alemão',
  'app_service.lang.de-DE': 'Alemão (Alemanha)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'Hebraico',
  'app_service.lang.ar': 'Árabe',
  'app_service.lang.ru': 'Russo',
  'app_service.lang.ru-RU': 'Russo (Rússia)',
  'app_service.lang.ru-BY': 'Russo (Bielorrússia)',
  'app_service.lang.ru-KZ': 'Russo (Cazaquistão)',
  'app_service.lang.ru-UA': 'Russo (Ucrânia)',
  'app_service.lang.uk': 'Ucraniano',
  'app_service.lang.be': 'Bielorrusso',
  'app_service.lang.kk': 'Cazaque',
  'app_service.lang.sr': 'Sérvio',
  'app_service.lang.ja': 'Japonês',
  'app_service.lang.ko': 'Coreano',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Holandês',
  'app_service.lang.tr': 'Turco',
  'app_service.lang.th': 'Tailandês',
  'app_service.lang.vi': 'Vietnamita',
  'app_service.lang.ms': 'Malaio',
  'app_service.lang.pl': 'Polonês',
  'app_service.lang.da': 'Dinamarquês',
  'app_service.lang.fi': 'Finlandês',
  'app_service.lang.la': 'Latim',
  'app_service.lang.no': 'Norueguês',
  'app_service.lang.sk': 'Eslovaco',
  'app_service.lang.bg': 'Búlgaro',
  'app_service.lang.fil': 'Filipino',
  'app_service.theme': 'Tema',
  'app_service.color_theme': 'Tema de cor',
  'app_service.dark_mode': 'Modo escuro',
  'app_service.sys_lang': 'Idioma do sistema',
  'app_service.select_theme': 'Selecionar tema',
};
