/// 俄语
Map<String, String> ru = {
  'app_service.language_tag': 'Языковая метка',
  'app_service.:': ':',
  'app_service.settings': 'Настройки',
  'app_service.close': 'Закрыть',
  'app_service.lang': 'Язык',
  'app_service.lang.zh': 'Китайский',
  'app_service.lang.zh_Hans': 'Китайский (упрощенный)',
  'app_service.lang.zh-MO': 'Китайский (Макао)',
  'app_service.lang.zh-HK': 'Китайский (Гонконг)',
  'app_service.lang.zh-TW': 'Китайский (Тайвань)',
  'app_service.lang.en': 'Английский',
  'app_service.lang.en-US': 'Английский (US)',
  'app_service.lang.en-GB': 'Английский (UK)',
  'app_service.lang.fr': 'Французский',
  'app_service.lang.de': 'Немецкий',
  'app_service.lang.de-DE': 'Немецкий (Германия)',
  'app_service.lang.it': 'Итальянский',
  'app_service.lang.he': 'Иврит',
  'app_service.lang.ar': 'Арабский',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Украинский',
  'app_service.lang.be': 'Белорусский',
  'app_service.lang.kk': 'Казахский',
  'app_service.lang.sr': 'Сербский',
  'app_service.lang.ja': 'Японский',
  'app_service.lang.ko': 'Корейский',
  'app_service.lang.pt': 'Португальский',
  'app_service.lang.nl': 'Нидерландский',
  'app_service.lang.tr': 'Турецкий',
  'app_service.lang.th': 'Тайский',
  'app_service.lang.vi': 'Вьетнамский',
  'app_service.lang.ms': 'Малайский',
  'app_service.lang.pl': 'Польский',
  'app_service.lang.da': 'Датский',
  'app_service.lang.fi': 'Финский',
  'app_service.lang.la': 'Латинский',
  'app_service.lang.no': 'Норвежский',
  'app_service.lang.sk': 'Словацкий',
  'app_service.lang.bg': 'Болгарский',
  'app_service.lang.fil': 'Филиппинский',
  'app_service.theme': 'Тема',
  'app_service.color_theme': 'Цветовая тема',
  'app_service.dark_mode': 'Темный режим',
  'app_service.sys_lang': 'Системный язык',
  'app_service.select_theme': 'Выбрать тему',
};
