/// 俄语
Map<String, String> ru = {
  'app_service.language': 'Язык',
  'app_service.languages': 'Языки',
  'app_service.select_language': 'Выбрать язык',
  'app_service.language_tag': 'Языковая метка',
  'app_service.:': ':',
  'app_service.settings': 'Настройки',
  'app_service.close': 'Закрыть',
  'app_service.lang': 'Язык',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Тема',
  'app_service.color_theme': 'Цветовая тема',
  'app_service.dark_mode': 'Темный режим',
  'app_service.sys_lang': 'Системный язык',
  'app_service.select_theme': 'Выбрать тему',
  // themes
  'aquaBlue': 'Аквамарин',
  'bahamaTrinidad': 'Багамские острова Тринидад',
  'barossa': 'Баросса',
  'amberBlue': 'Янтарно-синий',
  'bigStoneTulip': 'Тюльпан Биг-Стон',
  'blueDelight': 'Голубое наслаждение',
  'blueStoneTeal': 'Синий камень Чайка',
  'blueWhale': 'Синий кит',
  'blumine': 'Блюмин',
  'brandBlue': 'Фирменный синий',
  'brownOrange': 'Коричнево-оранжевый',
  'camaroneGreen': 'Камарон Зеленый',
  'damaskLunar': 'Дамаск Лунный',
  'deepBlueSea': 'Глубокое море',
  'deepPurple': 'Темно-фиолетовый',
  'dellGenoaGreen': 'Делл Генуя Зеленый',
  'ebonyClay': 'Черное дерево глина',
  'eggplantPurple': 'Баклажан Фиолетовый',
  'endeavourBlue': 'Предприимчивый Синий',
  'espressoCrema': 'Эспрессо Крем',
  'flutterDash': 'Флаш Спешить',
  'goldSunset': 'Золотой закат',
  'greens': 'Зелень',
  'greenForest': 'Зеленый лес',
  'greenJungle': 'Зеленый джунгли',
  'greenMoney': 'Зеленые деньги',
  'greyLaw': 'Серый закон',
  'hippieBlue': 'Хиппи Синий',
  'indigoNight': 'Индиго Ночь',
  'indigoSanMarino': 'Индиго Сан-Марино',
  'lipstickPink': 'Помада Розовый',
  'mallardValencia': 'Кряква Валенсия',
  'mangoMojito': 'Манго Мохито',
  'material3': 'Материал 3',
  'material3HighContrast': 'Материал 3 Высокий контраст',
  'material3Purple': 'Материал 3 Фиолетовый',
  'midnight': 'Полночь',
  'mosqueCyan': 'Мечеть Голубой',
  'ohMandyRed': 'О Мэнди Красный',
  'outerSpace': 'Космос',
  'pinkSakura': 'Розовые сакуры',
  'purpleBrown': 'Фиолетово-коричневый',
  'redBlue': 'Красный синий',
  'redTornado': 'Красный торнадо',
  'redWine': 'Красное вино',
  'rosewood': 'Палисандр',
  'rustDeepOrange': 'Ржавый глубокий оранжевый',
  'sanJuanBlue': 'Сан-Хуан Синий',
  'sharkOrange': 'Акула Оранжевый',
  'thunderbirdRed': 'Грозовой птицы Красный',
  'verdunGreen': 'Верден Зеленый',
  'verdunLime': 'Верден Лайм',
  'vesuviusBurned': 'Везувий Сожженный',
  'willowWasabi': 'Ива Васаби',
  'yukonGoldYellow': 'Юкон Золото Желтый',
};
