/// 塞尔维亚语
Map<String, String> sr = {
  'app_service.language': 'Језик',
  'app_service.languages': 'Језици',
  'app_service.select_language': 'Изаберите језик',
  'app_service.language_tag': 'Језичка ознака',
  'app_service.:': ':',
  'app_service.settings': 'Поставке',
  'app_service.close': 'Затвори',
  'app_service.lang': 'Језик',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Тема',
  'app_service.color_theme': 'Боја теме',
  'app_service.dark_mode': 'Тамни режим',
  'app_service.sys_lang': 'Језик система',
  'app_service.select_theme': 'Изаберите тему',
  // themes
  'aquaBlue': 'Аква плава',
  'bahamaTrinidad': 'Бахама Тринидад',
  'barossa': 'Бароса',
  'amberBlue': 'Јантарно плава',
  'bigStoneTulip': 'Велики камени тулумба',
  'blueDelight': 'Плаво задовољство',
  'blueStoneTeal': 'Плави каменски зелени',
  'blueWhale': 'Плава кита',
  'blumine': 'Блумин',
  'brandBlue': 'Бренд плава',
  'brownOrange': 'Браон наранџаста',
  'camaroneGreen': 'Камарон зелена',
  'damaskLunar': 'Дамаск Лунар',
  'deepBlueSea': 'Дубоко плаво море',
  'deepPurple': 'Дубока лилава',
  'dellGenoaGreen': 'Дел Геноа Зелено',
  'ebonyClay': 'Ебони глина',
  'eggplantPurple': 'Плава патлиџана',
  'endeavourBlue': 'Ендевор плава',
  'espressoCrema': 'Еспресо крем',
  'flutterDash': 'Флатер Даш',
  'goldSunset': 'Златни сумрак',
  'greens': 'Зелена',
  'greenForest': 'Зелена шума',
  'greenJungle': 'Зелена џунгла',
  'greenMoney': 'Зелени новац',
  'greyLaw': 'Сиво право',
  'hippieBlue': 'Хипи плава',
  'indigoNight': 'Индиго ноћ',
  'indigoSanMarino': 'Индиго Сан Марино',
  'lipstickPink': 'Ружићаста пинк',
  'mallardValencia': 'Малард Валенциа',
  'mangoMojito': 'Манго мојито',
  'material3': 'Материјал 3',
  'material3HighContrast': 'Материјал 3 Висок контраст',
  'material3Purple': 'Материјал 3 Лила',
  'midnight': 'Полуноћ',
  'mosqueCyan': 'Дзамија цијан',
  'ohMandyRed': 'О, Манди црвено',
  'outerSpace': 'Спољни простор',
  'pinkSakura': 'Роза сакура',
  'purpleBrown': 'Плаво кафеава',
  'redBlue': 'Црвено плава',
  'redTornado': 'Црвена вихор',
  'redWine': 'Црвено вино',
  'rosewood': 'Ружичасто дрво',
  'rustDeepOrange': 'Рђаво дубока наранџаста',
  'sanJuanBlue': 'Сан Хуан плава',
  'sharkOrange': 'Ајкула наранџаста',
  'thunderbirdRed': 'Тандерберд црвено',
  'verdunGreen': 'Вердун зелено',
  'verdunLime': 'Вердун лимета',
  'vesuviusBurned': 'Везувијски спаљен',
  'willowWasabi': 'Вилоу Васаби',
  'yukonGoldYellow': 'Јукон Златно жуто',
};
