/// 塞尔维亚语
Map<String, String> sr = {
  'app_service.language_tag': 'Језичка ознака',
  'app_service.:': ':',
  'app_service.settings': 'Поставке',
  'app_service.close': 'Затвори',
  'app_service.lang': 'Језик',
  'app_service.lang.zh': 'Кинески',
  'app_service.lang.zh_Hans': 'Кинески (поједностављен)',
  'app_service.lang.zh-MO': 'Кинески (Макао)',
  'app_service.lang.zh-HK': 'Кинески (Хонг Конг)',
  'app_service.lang.zh-TW': 'Кинески (Тајван)',
  'app_service.lang.en': 'Енглески',
  'app_service.lang.en-US': 'Енглески (US)',
  'app_service.lang.en-GB': 'Енглески (UK)',
  'app_service.lang.fr': 'Француски',
  'app_service.lang.de': 'Немачки',
  'app_service.lang.de-DE': 'Немачки (Немачка)',
  'app_service.lang.it': 'Италијански',
  'app_service.lang.he': 'Хебрејски',
  'app_service.lang.ar': 'Арапски',
  'app_service.lang.ru': 'Руски',
  'app_service.lang.ru-RU': 'Руски (Русија)',
  'app_service.lang.ru-BY': 'Руски (Белорусија)',
  'app_service.lang.ru-KZ': 'Руски (Казахстан)',
  'app_service.lang.ru-UA': 'Руски (Украјина)',
  'app_service.lang.uk': 'Украјински',
  'app_service.lang.be': 'Белоруски',
  'app_service.lang.kk': 'Казашки',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': 'Јапански',
  'app_service.lang.ko': 'Корејски',
  'app_service.lang.pt': 'Португалски',
  'app_service.lang.nl': 'Холандски',
  'app_service.lang.tr': 'Турски',
  'app_service.lang.th': 'Тајландски',
  'app_service.lang.vi': 'Вијетнамски',
  'app_service.lang.ms': 'Малајски',
  'app_service.lang.pl': 'Пољски',
  'app_service.lang.da': 'Дански',
  'app_service.lang.fi': 'Фински',
  'app_service.lang.la': 'Латински',
  'app_service.lang.no': 'Норвешки',
  'app_service.lang.sk': 'Словачки',
  'app_service.lang.bg': 'Бугарски',
  'app_service.lang.fil': 'Филипински',
  'app_service.theme': 'Тема',
  'app_service.color_theme': 'Боја теме',
  'app_service.dark_mode': 'Тамни режим',
  'app_service.sys_lang': 'Језик система',
  'app_service.select_theme': 'Изаберите тему',
};
