/// 乌克兰语
Map<String, String> uk = {
  'app_service.language': 'Мова',
  'app_service.languages': 'Мови',
  'app_service.select_language': 'Вибрати мову',
  'app_service.language_tag': 'Мовний прапорець',
  'app_service.:': ':',
  'app_service.settings': 'Налаштування',
  'app_service.close': 'Закрити',
  'app_service.lang': 'Мова',
  'app_service.lang.zh': '中文',
  'app_service.lang.zh_Hans': '中文（简体）',
  'app_service.lang.zh-MO': '中文（澳门）',
  'app_service.lang.zh-HK': '中文（香港）',
  'app_service.lang.zh-TW': '中文（台湾）',
  'app_service.lang.en': 'English',
  'app_service.lang.en-US': 'English (US)',
  'app_service.lang.en-GB': 'English (UK)',
  'app_service.lang.fr': 'Français',
  'app_service.lang.de': 'Deutsch',
  'app_service.lang.de-DE': 'Deutsch (Deutschland)',
  'app_service.lang.it': 'Italiano',
  'app_service.lang.he': 'עברית',
  'app_service.lang.ar': 'العربية',
  'app_service.lang.ru': 'Русский',
  'app_service.lang.ru-RU': 'Русский (Россия)',
  'app_service.lang.ru-BY': 'Русский (Беларусь)',
  'app_service.lang.ru-KZ': 'Русский (Казахстан)',
  'app_service.lang.ru-UA': 'Русский (Украина)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Беларуская',
  'app_service.lang.kk': 'Қазақ',
  'app_service.lang.sr': 'Српски',
  'app_service.lang.ja': '日本語',
  'app_service.lang.ko': '한국어',
  'app_service.lang.pt': 'Português',
  'app_service.lang.nl': 'Nederlands',
  'app_service.lang.tr': 'Türkçe',
  'app_service.lang.th': 'ไทย',
  'app_service.lang.vi': 'Tiếng Việt',
  'app_service.lang.ms': 'Bahasa Melayu',
  'app_service.lang.pl': 'Polski',
  'app_service.lang.da': 'Dansk',
  'app_service.lang.fi': 'Suomi',
  'app_service.lang.la': 'Latina',
  'app_service.lang.no': 'Norsk',
  'app_service.lang.sk': 'Slovenčina',
  'app_service.lang.bg': 'Български',
  'app_service.theme': 'Тема',
  'app_service.color_theme': 'Колірна тема',
  'app_service.dark_mode': 'Темний режим',
  'app_service.sys_lang': 'Системна мова',
  'app_service.select_theme': 'Вибрати тему',
  // themes
  'aquaBlue': 'Блакитний',
  'bahamaTrinidad': 'Багамський Тринідад',
  'barossa': 'Баросса',
  'amberBlue': 'Бурштиново-синій',
  'bigStoneTulip': 'Великий камінь Тюльпан',
  'blueDelight': 'Синій задоволення',
  'blueStoneTeal': 'Синій камінь Тіл',
  'blueWhale': 'Синя кит',
  'blumine': 'Блюмін',
  'brandBlue': 'Брендовий синій',
  'brownOrange': 'Коричневий апельсин',
  'camaroneGreen': 'Камарон зелений',
  'damaskLunar': 'Дамаський місячний',
  'deepBlueSea': 'Глибоке море',
  'deepPurple': 'Глибокий фіолетовий',
  'dellGenoaGreen': 'Дель Генуезький зелений',
  'ebonyClay': 'Ебенова глина',
  'eggplantPurple': 'Баклажановий фіолетовий',
  'endeavourBlue': 'Ендеавор синій',
  'espressoCrema': 'Еспресо з кремом',
  'flutterDash': 'Флап-даш',
  'goldSunset': 'Золотий захід сонця',
  'greens': 'Зелені',
  'greenForest': 'Зелений ліс',
  'greenJungle': 'Зелений джунглі',
  'greenMoney': 'Зелений гроші',
  'greyLaw': 'Сірий закон',
  'hippieBlue': 'Хіппі синій',
  'indigoNight': 'Індіго Ніч',
  'indigoSanMarino': 'Сан-Марино Індіго',
  'lipstickPink': 'Губна помада рожева',
  'mallardValencia': 'Качка Валенсія',
  'mangoMojito': 'Манго Мохіто',
  'material3': 'Матеріал 3',
  'material3HighContrast': 'Матеріал 3 висококонтрастний',
  'material3Purple': 'Матеріал 3 Фіолетовий',
  'midnight': 'Північ',
  'mosqueCyan': 'Мечеть ціан',
  'ohMandyRed': 'О, Менді Червоний',
  'outerSpace': 'Зовнішній простір',
  'pinkSakura': 'Рожевий сакура',
  'purpleBrown': 'Фіолетовий коричневий',
  'redBlue': 'Червоний синій',
  'redTornado': 'Червоний торнадо',
  'redWine': 'Червоне вино',
  'rosewood': 'Рожеве дерево',
  'rustDeepOrange': 'Ржавчина глибокого апельсину',
  'sanJuanBlue': 'Сан-Хуан синій',
  'sharkOrange': 'Акула оранжева',
  'thunderbirdRed': 'Тандербірд Червоний',
  'verdunGreen': 'Верден зелений',
  'verdunLime': 'Верден Лайм',
  'vesuviusBurned': 'Везувій згорів',
  'willowWasabi': 'Вілловий Васабі',
  'yukonGoldYellow': 'Юкон золотий жовтий',
};
