/// 乌克兰语
Map<String, String> uk = {
  'app_service.language_tag': 'Мовний прапорець',
  'app_service.:': ':',
  'app_service.settings': 'Налаштування',
  'app_service.close': 'Закрити',
  'app_service.lang': 'Мова',
  'app_service.lang.zh': 'Китайська',
  'app_service.lang.zh_Hans': 'Китайська (спрощена)',
  'app_service.lang.zh-MO': 'Китайська (Макао)',
  'app_service.lang.zh-HK': 'Китайська (Гонконг)',
  'app_service.lang.zh-TW': 'Китайська (Тайвань)',
  'app_service.lang.en': 'Англійська',
  'app_service.lang.en-US': 'Англійська (US)',
  'app_service.lang.en-GB': 'Англійська (UK)',
  'app_service.lang.fr': 'Французька',
  'app_service.lang.de': 'Німецька',
  'app_service.lang.de-DE': 'Німецька (Німеччина)',
  'app_service.lang.it': 'Італійська',
  'app_service.lang.he': 'Іврит',
  'app_service.lang.ar': 'Арабська',
  'app_service.lang.ru': 'Російська',
  'app_service.lang.ru-RU': 'Російська (Росія)',
  'app_service.lang.ru-BY': 'Російська (Білорусь)',
  'app_service.lang.ru-KZ': 'Російська (Казахстан)',
  'app_service.lang.ru-UA': 'Російська (Україна)',
  'app_service.lang.uk': 'Українська',
  'app_service.lang.be': 'Білоруська',
  'app_service.lang.kk': 'Казахська',
  'app_service.lang.sr': 'Сербська',
  'app_service.lang.ja': 'Японська',
  'app_service.lang.ko': 'Корейська',
  'app_service.lang.pt': 'Португальська',
  'app_service.lang.nl': 'Нідерландська',
  'app_service.lang.tr': 'Турецька',
  'app_service.lang.th': 'Тайська',
  'app_service.lang.vi': 'Вʼєтнамська',
  'app_service.lang.ms': 'Малайська',
  'app_service.lang.pl': 'Польська',
  'app_service.lang.da': 'Данська',
  'app_service.lang.fi': 'Фінська',
  'app_service.lang.la': 'Латинська',
  'app_service.lang.no': 'Норвезька',
  'app_service.lang.sk': 'Словацька',
  'app_service.lang.bg': 'Болгарська',
  'app_service.lang.fil': 'Філіппінська',
  'app_service.theme': 'Тема',
  'app_service.color_theme': 'Колірна тема',
  'app_service.dark_mode': 'Темний режим',
  'app_service.sys_lang': 'Системна мова',
  'app_service.select_theme': 'Вибрати тему',
};
